# Shared helpers for install.sh and the installed muv command.

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  printf 'muv.sh is a private library; run install.sh or muv instead.\n' >&2
  exit 2
fi

MUV_LOG_NAME="${MUV_LOG_NAME:-muv}"
MUV_VERSION="${MUV_VERSION:-0.1.0}"

log()  { printf '\033[1;32m[%s]\033[0m %s\n' "$MUV_LOG_NAME" "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

run_uv() {
  PATH="$UV_ROOT/bin:$PATH" \
  UV_CACHE_DIR="$UV_ROOT/cache" UV_PYTHON_INSTALL_DIR="$UV_ROOT/python" \
  UV_PYTHON_CACHE_DIR="$UV_ROOT/python-cache" UV_MANAGED_PYTHON=true \
  UV_PYTHON_BIN_DIR="$UV_ROOT/bin" UV_LINK_MODE=hardlink \
  UV_PYTHON_DOWNLOADS=manual "$UV_ROOT/bin/uv" "$@"
}

pick_fastest_index() {
  local out url
  out="$(PATH="$UV_ROOT/bin:$PATH" \
         UV_CACHE_DIR="$UV_ROOT/cache" UV_PYTHON_INSTALL_DIR="$UV_ROOT/python" \
         UV_PYTHON_CACHE_DIR="$UV_ROOT/python-cache" UV_MANAGED_PYTHON=true \
         UV_PYTHON_BIN_DIR="$UV_ROOT/bin" UV_LINK_MODE=hardlink \
         UV_PYTHON_DOWNLOADS=manual \
         "$UV_ROOT/bin/uvx" cnpip list 2>/dev/null)" || return 1
  url="$(printf '%s\n' "$out" \
    | awk '/ms/ && /https?:\/\// {for(i=1;i<=NF;i++) if($i ~ /^https?:\/\//){print $i; exit}}')"
  [ -n "$url" ] && { printf '%s\n' "$url"; return 0; } || return 1
}

read_config_var() {
  local name="$1"
  [[ "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || return 2
  [ -f "$CONFIG_FILE" ] || return 1
  (
    . "$CONFIG_FILE"
    printf '%s\n' "${!name-}"
  )
}

write_runtime_config() {
  local index_url="${1:-}" existing_index tmp
  [ -d "$UV_ROOT" ] || die "未找到 $UV_ROOT，请先执行 install.sh"
  if [ -z "$index_url" ]; then
    existing_index="$(read_config_var MUV_DEFAULT_INDEX 2>/dev/null || true)"
    index_url="$existing_index"
  fi
  tmp="$CONFIG_FILE.tmp.$$"
  {
    printf '# Generated by muv. Do not commit machine-specific values.\n'
    printf 'MUV_GROUP=%s\n' "$(shell_quote "$UV_GROUP")"
    if [ -n "$index_url" ]; then
      printf 'MUV_DEFAULT_INDEX=%s\n' "$(shell_quote "$index_url")"
    fi
  } > "$tmp" || die "写入失败: $tmp"
  mv "$tmp" "$CONFIG_FILE" || die "写入失败: $CONFIG_FILE"
  chown root:"$UV_GROUP" "$CONFIG_FILE" 2>/dev/null || true
  chmod 0664 "$CONFIG_FILE" 2>/dev/null || true
}

write_index() {
  local url="$1"
  [ -f "$ENV_FILE" ] || die "未找到 $ENV_FILE，请先执行 install.sh"
  write_runtime_config "$url"
  [ "$(read_config_var MUV_DEFAULT_INDEX 2>/dev/null || true)" = "$url" ] \
    || die "写入失败，请检查 $CONFIG_FILE"
  log "镜像源已写入 $CONFIG_FILE: $url"
}

bootstrap_uv() {
  local dest="$1"
  command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 \
    || die "需要 curl 或 wget 下载 uv，或手动把 uv/uvx 放入 bin/ 后重试"
  log "未找到 uv 二进制，从 astral.sh 下载到 $dest"
  mkdir -p "$dest"
  local -a fetch_cmd
  if command -v curl >/dev/null 2>&1; then
    fetch_cmd=(curl -LsSf https://astral.sh/uv/install.sh)
  else
    fetch_cmd=(wget -qO- https://astral.sh/uv/install.sh)
  fi
  "${fetch_cmd[@]}" | env UV_INSTALL_DIR="$dest" UV_NO_MODIFY_PATH=1 INSTALLER_NO_MODIFY_PATH=1 sh \
    || die "uv 下载/安装失败"
  [ -x "$dest/uv" ] && [ -x "$dest/uvx" ] || die "下载后仍未找到 $dest/uv（或 uvx）"
}

acquire_muv_lock() {
  local lock_file="$UV_ROOT/.muv.lock"
  exec 9>"$lock_file" || die "无法创建锁文件: $lock_file"
  if command -v flock >/dev/null 2>&1; then
    flock -n 9 || die "另一个 muv 操作正在执行"
  else
    warn "未找到 flock，无法启用并发保护"
  fi
  chown root:"$UV_GROUP" "$lock_file" 2>/dev/null || true
  chmod 0664 "$lock_file" 2>/dev/null || true
}

# root 在 sticky 缓存目录里留下的普通文件，会被 Linux fs.protected_regular
# 拦截（非 root 用户无法 open root 拥有的文件，即使权限位是 666）。
# 此函数将 root 拥有的缓存文件转交给实际操作者（SUDO_USER 或 uvusers 成员）。
# 仅在 root 身份下有效。
fix_root_cache() {
  [ "$(id -u)" -eq 0 ] || return 0
  [ -d "$UV_ROOT/cache" ] || return 0

  local target=""
  # 优先用 SUDO_USER（谁跑的 sudo install.sh）
  [ -n "${SUDO_USER:-}" ] && id "$SUDO_USER" &>/dev/null && target="$SUDO_USER"
  # 回退：取 uvusers 组的第一个成员
  [ -z "$target" ] && target=$(getent group "$UV_GROUP" 2>/dev/null | cut -d: -f4 | cut -d, -f1)
  [ -n "$target" ] || return 0

  local count
  count=$(find "$UV_ROOT/cache" -mindepth 1 -user root -type f -printf . 2>/dev/null | wc -c)
  [ "$count" -gt 0 ] || return 0

  find "$UV_ROOT/cache" -mindepth 1 -user root -type f \
    -exec chown "$target:$UV_GROUP" {} + 2>/dev/null || true
  log "已修复 $count 个 root 拥有的缓存文件 -> $target"
}

# 检查缓存中是否有 root 拥有的文件（doctor 用）。
# 返回文件数（0 表示无问题）。
check_root_cache() {
  [ -d "$UV_ROOT/cache" ] || { printf '%s\n' "0"; return; }
  find "$UV_ROOT/cache" -mindepth 1 -user root -type f -printf . 2>/dev/null | wc -c
}
